# Python Dasar

## 1. Hello World

In [9]:
print('Hello World')

Hello World


## 2. Variabel 
### - Spesifik, *case sensitive* ,  dan dapat dipanggil melalui nama variabel

In [13]:
tinggi = 1.65
berat = 55

In [3]:
tinggi

1.65

In [6]:
tinggi = 1.78 # Meter
berat = 70 # Kilogram

In [7]:
70 / 1.78 ** 2

22.093170054286073

In [8]:
berat / tinggi ** 2

22.093170054286073

In [13]:
bmi = berat / tinggi ** 2

In [14]:
bmi

22.093170054286073

In [18]:
tinggi = 1.78
berat = 70 # Coba ganti berat dengan angka yang lain apa yang terjadi?
bmi = berat / tinggi ** 2
bmi

22.093170054286073

## Tipe Data

In [22]:
type(bmi)

float

In [21]:
jumlah_hari = 7

In [18]:
type(jumlah_hari)

int

In [24]:
x = 'BMI itu apa?'
y = 'Haha'

In [25]:
type(x)

str

In [26]:
type(y)

str

In [27]:
print(type(x), type(y))

<class 'str'> <class 'str'>


In [28]:
z = True
type(z)

bool

### Tipe Data Python
- float - Bilangan real
- int - Bilangan Bulat
- str - string,text
- bool - True, False

## 3.List Python

### Permasalahan
- Data Science: Banyak data
- Misalkan ada beberapa data tinggi

In [30]:
tinggi_1 = 1.34
tinggi_2 = 1.69
tinggi_3 = 1.82
tinggi_4 = 1.99

#### Sangat tidak efisien

### List Python [a,b,c]

In [31]:
[1.73, 1.68, 1.71, 1.89]

[1.73, 1.68, 1.71, 1.89]

In [32]:
keluarga = [1.73, 1.68, 1.71, 1.89]
keluarga

[1.73, 1.68, 1.71, 1.89]

## 4.Numpy

In [35]:
tinggi = [1.73, 1.68, 1.71, 1.89, 1.69]

In [36]:
tinggi

[1.73, 1.68, 1.71, 1.89, 1.69]

In [37]:
berat = [65.4, 59.2, 63.6, 88.4, 68.7]

In [38]:
berat / tinggi ** 2 #error karena perkalian array

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Solusi? Numpy

- Python Numerik 
- Alternatif dari list python: NumPy Array
- Kalkulasi semua elemen array
- Mudah dan Cepat

In [44]:
import numpy as np
np_tinggi = np.array(tinggi)
np_tinggi

array([1.73, 1.68, 1.71, 1.89, 1.69])

In [40]:
np_berat = np.array(berat)
np_berat

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [41]:
bmi = np_berat / np_tinggi ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 24.05377963])

## 5. Pandas

## Apa itu pandas

- Library Python untuk analisis Data dengan performa tinggi
- Struktur data dengan banyak fungsi
  - Label yang bermakna
  - Time series
  - Operasi relasional
  - Mampu menangani data yang hilang

In [45]:
negara = {
"country":["Brazil", "Russia", "India", "China", "South Africa"],
"capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
"area":[8.516, 17.10, 3.286, 9.597, 1.221],
"population":[200.4, 143.5, 1252, 1357, 52.98] }

In [2]:
import pandas as pd

In [47]:
negara_df = pd.DataFrame(negara)
negara_df

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [48]:
negara_df.index = ["BR", "RU", "IN", "CH", "SA"]
negara_df

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

### DataFrame dari CSV

In [3]:
df = pd.read_csv('negara.csv')
df

Unnamed: 0       country    capital    area  population
0         BR        Brazil   Brasilia   8.516      200.40
1         RU        Russia     Moscow  17.100      143.50
2         IN         India  New Delhi   3.286     1252.00
3         CH         China    Beijing   9.597     1357.00
4         SA  South Africa   Pretoria   1.221       52.98

In [6]:
df = pd.read_csv('negara.csv', index_col=0)
df

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [11]:
df['country']

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [14]:
df[['country', 'capital']]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [15]:
df.loc[:, ["country", "capital"]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [31]:
df.loc[:,"country":"population"]

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [18]:
df.iloc[0:2]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5

In [19]:
df.iloc[0:2, 2]

BR     8.516
RU    17.100
Name: area, dtype: float64

In [21]:
df.iloc[0:2, 2:4]

area  population
BR   8.516       200.4
RU  17.100       143.5

In [29]:
df.iloc[0:2, -4]

BR    Brazil
RU    Russia
Name: country, dtype: object